theme: jekyll-theme-slate

title: Homebase
description: Under development

# social links
email: danhong.23@outlook.com
linkedin_username: danhong23
github: dnaeye

# plugins
plugins:
  - jemoji

# show_downloads: true
